spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/airlinemanager
    username: postgres
    password: abdul1
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # 24 hours
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
